kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: zabbix
  name: mysql-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /MYSQL
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-claim
  namespace: zabbix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi