kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: zabbix
  name: zabbix-server-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/externalscripts"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zabbix-server-laim
  namespace: zabbix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi