apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: zabbix-web
spec:
  selector:
    matchLabels:
      app: zabbix-web
  template:
    metadata:
      namespace: monitoring
      labels:
        app: zabbix-web
    spec:
      containers:
      - name: zabbix-web
        image: zabbix/zabbix-web-nginx-mysql
        ports:
        - containerPort: 8080
        env:
        - name: DB_SERVER_HOST
          value: 192.168.0.55
        - name: MYSQL_USER
          value: zabbix
        - name: MYSQL_PASSWORD
          value: zabbix
        # - name: ZBX_SERVER_HOST
        #   value: 192.168.0.55
        # - name: ZBX_SERVER_PORT
        #   value: "30757"
        - name: PHP_TZ
          value: America/Belem
