apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: zabbix
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
      namespace: zabbix
    spec:
      securityContext:
        runAsUser: 472
        fsGroup: 472
      containers:
      - name: grafana
        image: grafana/grafana
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: admin
        - name: GF_INSTALL_PLUGINS
          value: alexanderzobnin-zabbix-app 3.12.0,snuids-radar-panel,magnesium-wordcloud-panel,grafana-clock-panel,grafana-piechart-panel,camptocamp-prometheus-alertmanager-datasource,vonage-status-panel,grafana-worldmap-panel,raintank-worldping-app,agenty-flowcharting-panel
        ports:
        - containerPort: 3000
          volumeMounts:
          - name: grafana
            mountPath: /var/lib/grafana
      volumes:
       - hostPath:
          path: /grafana
         name: grafana