apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: grafana
spec:
  selector:
    app: grafana
  ports:
  - name: grafana-http
    type: NodePort
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30000