apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
spec:
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
      - name: zabbix-server
        image: zabbix/zabbix-server-mysql:alpine-5.0-latest
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 10051
          name: server
          protocol: TCP
        env:
        - name: MYSQL_DATABASE
          value: zabbix
        - name: MYSQL_USER
          value: zabbix
        - name: MYSQL_PASSWORD
          value: zabbix
        - name: MYSQL_ROOT_PASSWORD
          value: root_pwd
        - name: DB_SERVER_HOST
          value: 170.82.181.4
        - name: DB_SERVER_PORT
          value: 15802