apiVersion: v1
kind: PersistentVolume
metadata:
  name: zabbiz-pv-server
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt"
