apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: monitoring
  name: zabbiz-pv-server
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt"
