apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: zabbix-server
spec:
  selector:
    app: zabbix-server
  ports:
  - name: zabbix-trapper
    type: NodePort
    protocol: TCP
    port: 10051
    targetPort: 10051
    nodePort: 3005