apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
  namespace: monitoring
spec:
  selector:
    app: zabbix-server
  ports:
  - name: zabbix-trapper
    protocol: TCP
    port: 10051
    targetPort: 10051
    nodePort: 30051
  type: NodePort