apiVersion: v1
kind: Service
metadata:
  annotations:
    generated: by 8gwifi.org
  name: zabbix-web
  namespace: default
spec:
  externalIPs:
  - 192.168.0.80
  loadBalancerIP: 192.168.0.1
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: zabbix-web
  sessionAffinity: None
  type: LoadBalancer
