apiVersion: v1
kind: Service
metadata:
  annotations:
    generated: by 8gwifi.org
  name: zabbix-web
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    server: web-zabbix
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    generated: by 8gwifi.org
  name: zabbix-server
  namespace: default
spec:
  ports:
  - name: server51
    port: 10051
    protocol: TCP
    targetPort: 10051
  - name: server52
    port: 10052
    protocol: TCP
    targetPort: 10052
  selector:
    server: server-zabbix
  sessionAffinity: None
  type: ClusterIP