kind: PersistentVolume
apiVersion: v1
metadata:
  name: zabbix-mysql-data
  labels:
    type: local
  namespace: zabbix
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zabbix-mysql-data-claim
  namespace: zabbix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: zabbix-mysql-data