apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web
spec:
  selector:
    matchLabels:
      app: zabbix-web
  template:
    metadata:
      labels:
        app: zabbix-web
    spec:
      containers:
      - name: zabbix-web
        image: zabbix/zabbix-web-nginx-mysql
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_DATABASE
          value: zabbix
        - name: MYSQL_USER
          value: zabbix
        - name: MYSQL_PASSWORD
          value: zabbix
        - name: MYSQL_ROOT_PASSWORD
          value: root_pwd
        - name: DB_SERVER_HOST
          value: 170.82.181.4
        - name: DB_SERVER_PORT
          value: "15802"
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-web
spec:
  selector:
    app: zabbix-web
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: NodePort
