apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
      namespace: default
    spec:
      containers:
      - image: 'zabbix/zabbix-web-nginx-mysql'
        imagePullPolicy: IfNotPresent
        name: zabbix-web
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8443
          name: https
          protocol: TCP
        env:
        - name: ZBX_SERVER_NAME
          value: zabbixweb
        - name: MYSQL_DATABASE
          value: zabbix
        - name: MYSQL_USER
          value: zabbix
        - name: MYSQL_PASSWORD
          value: zabbix
        - name: MYSQL_ROOT_PASSWORD
          value: root_pwd
        - name: DB_SERVER_HOST
          value: 192.168.0.55
        - name: ZBX_SERVER_HOST
          value: 10.152.183.243
