apiVersion: v1
kind: Service
metadata:
  name: zabbix-web
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: web
  sessionAffinity: None
  type: NodePort